dist: trusty
language: node_js
node_js:
  - 8
  - 6
  - 4

install: npm install

script: npm run build

after_success:
  - npm run doc
  - echo 'node_modules' > .gitignore
  - echo $CNAME > CNAME

cache:
  yarn: true
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    node: '8'
